package com.rational.model.enums;

public enum SpellSearchParam {
    DESCRIPTION, NAME, LEVEL, SAVE, SCHOOL, CLASS, VERBAL_COMPONENTS, SOMATIC_COMPONENTS, MATERIAL_COMPONENTS, ATTACK, RITUAL, CONCENTRATION;
}
